[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="reports/accueil.html"
    path = "" #la racine du site

    [[plugins.inputs.audits]]
    output_path="reports/contact.html"
    path = "/fr/contact.html"

    [[plugins.inputs.audits]]
    output_path="reports/artiste.html"
    path = "/fr/c-cliff.html" 

    [[plugins.inputs.audits]]
    output_path="reports/oeuvre.html"
    path = "/fr/alchemist.html" 

    [[plugins.inputs.audits]]
    output_path="reports/en-savoir-plus.html"
    path = "/fr/en-savoir-plus.html" 